
#ifndef HAIBLOCK_RES_H
#define HAIBLOCK_RES_H

// WARNING: DO NOT MODIFY THIS FILE
// AUTO-GENERATED BY BREW Resource Editor

#define HAIBLOCK_RES_FILE "haiblock.bar"

#define IMG_BLOCK		1


#endif  // HAIBLOCK_RES_H
