
#ifndef HAISND_RES_H
#define HAISND_RES_H

// WARNING: DO NOT MODIFY THIS FILE
// AUTO-GENERATED BY BREW Resource Editor

#define HAISND_RES_FILE "HaiSnd.bar"

#define SND_0		1
#define SND_1		2
#define SND_2		3
#define SND_3		4
#define SND_4		5
#define SND_5		6
#define SND_6		7
#define SND_7		8
#define SND_8		9
#define SND_9		10
#define SND_10		11
#define SND_11		12
#define SND_12		13
#define SND_13		14
#define SND_14		15
#define SND_15		16


#endif  // HAISND_RES_H
